### PR TITLE
fix: Server shutdown grace period

### LINKED ISSUE #389: Server graceful shutdown does not allow enough time for requests from external load balancer or istio sidecar to complete
**What happened**:
When using Open Saves with Istio, the Open Saves server shutdown sequence does not allow the Envoy proxy enough time to drain in flight requests.

**What you expected to happen**:
All in-flight messages that are getting routed through Istio to drain successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Trigger a termination of multiple Open Saves containers running in Kubernetes either manually or when rolling out a new version of the service.

**Anything else we need to know?**:

**Environment**:
- Open Saves version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by loranger2k**
**What type of PR is this?**
/kind fix

**What this PR does / Why we need it**:
To fix an issue with dropped connection in Open Saves when used with Istio. The shutdown grace period has been added to the yaml file for customization (default to 5s).

**Which issue(s) this PR fixes**:
Closes #389

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hongalex — APPROVED** [review]

File: internal/app/server/open_saves_test.go [hunk 1]
```diff
@@ -124,6 +126,8 @@ func TestOpenSaves_HealthCheck(t *testing.T) {
 	if want := healthgrpc.HealthCheckResponse_NOT_SERVING; got.Status != want {
 		t.Errorf("hc.Check got: %v, want: %v", got.Status, want)
 	}
+	// Sleep long enough to free up the connection
+	time.Sleep(serviceConfig.ShutdownGracePeriod)
```
Comment (yuryu) [inline internal/app/server/open_saves_test.go:130]: Perhaps we don't need to sleep in tests?

File: internal/app/server/open_saves_test.go [hunk 2]
```diff
@@ -148,6 +152,8 @@ func TestOpenSaves_RunServer(t *testing.T) {
 			t.Errorf("got err calling server.Run: %v", err)
 		}
 	})
+	// Sleep long enough to free up the connection
+	time.Sleep(serviceConfig.ShutdownGracePeriod)
```
Comment (yuryu) [inline internal/app/server/open_saves_test.go:156]: ditto

File: internal/app/server/open_saves_test.go (hunk 1 above)
Comment (loranger2k) [reply internal/app/server/open_saves_test.go:130]: We need to sleep if we set the grace period to be 1s. If we set it to 0s, then we would not need to sleep.

File: internal/app/server/open_saves_test.go (hunk 2 above)
Comment (loranger2k) [reply internal/app/server/open_saves_test.go:156]: same comment as above. If we do not sleep, we get an error when starting the next test since the port is still in use. I found that out from looking at the test logs in GCP.
