### PR TITLE
fix: remove extra writes when uploading chunked data

### LINKED ISSUE #403: Remove more than once chunkRef write
**What happened**:
UploadChunk creates multiple writes to the ChunkRef datastore entity. This is because a ChunkRef is created initially and then eventually marked as Ready after the blob is uploaded to GCS.

At best this is inefficient, and at worst causes contention.

**What you expected to happen**:
Only one write is made to the chunkref entity.

**How to reproduce it (as minimally and precisely as possible)**:
Upload a Chunk

**Anything else we need to know?**:

We can remove this by creating the ChunkRef after the blob is created. If this upload fails, we can cancel the blob write.

**Environment**:
- Open Saves version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by loranger2k**
/kind fix

**What this PR does / Why we need it**:
During chunk upload, open saves is doing multiple write operations on the same chunk entity. We have removed one write to follow best practices for Datastore and reduce database contention.

**Which issue(s) this PR fixes**:
Closes #403 

**Special notes for your reviewer**:

### CODE REVIEW

File: internal/app/server/open_saves.go [hunk 1]
```diff
@@ -539,21 +532,27 @@ func (s *openSavesServer) UploadChunk(stream pb.OpenSaves_UploadChunkServer) err
...
+	deleteOnExit := true
 	defer func() {
 		if writer != nil {
 			writer.Close()
-			// This means an abnormal exit, so make sure to mark the blob as Fail.
-			s.chunkRefFail(ctx, chunk)
+		}
+		if deleteOnExit {
+			// Delete the object from GS if there are errors uploading the data or inserting a chunkref
+			if derr := s.blobStore.Delete(ctx, chunk.ObjectPath()); derr != nil {
```
Comment (hongalex) [inline internal/app/server/open_saves.go:553]: I think this part can be simplified by cancelling the context that is passed into `s.blobstore.NewWriter`. That is, create a new cancellable context there and call `cancel()` instead of making another call to `s.blobstore.Delete`.

File: internal/app/server/open_saves_test.go [hunk 2]
```diff
@@ -52,8 +52,8 @@ import (
 )
 
 const (
-	testProject             = "triton-for-games-dev"
-	testBucket              = "gs://triton-integration"
+	testProject             = "dev-triton"
```
Comment (hongalex) [inline internal/app/server/open_saves_test.go:55]: Revert these prior to merging.

Comment (loranger2k) [reply internal/app/server/open_saves_test.go]: Oops. Reverted.

File: internal/app/server/open_saves.go (hunk 1 above)
Comment (loranger2k) [reply internal/app/server/open_saves.go:553]: Do you know if calling cancel() on the new context that is passed to the Writer will do anything once the object has been successfully uploaded to GS?

The upload might succeed but the comparison to the hash values might fail, or the chunkref insert might also fail. So we need the object in GS to be deleted even then.

Comment (hongalex) [reply internal/app/server/open_saves.go:553]: If you cancel the context prior to the writer being closed, then GCS won't save the object. [Source](https://gocloud.dev/howto/blob/#:~:text=In%20some%20cases,failure%20is%20expected.).

**Review by hongalex — APPROVED** [review]

File: internal/pkg/metadb/metadb.go [hunk 3]
```diff
@@ -938,22 +946,6 @@ func (m *MetaDB) MarkChunkRefReady(ctx context.Context, chunk *chunkref.ChunkRef
 	return err
 }
 
-// InsertChunkRef inserts a new ChunkRef object to the datastore.
-func (m *MetaDB) InsertChunkRef(ctx context.Context, chunk *chunkref.ChunkRef) error {
```
Comment (hongalex) [inline internal/pkg/metadb/metadb.go:942]: Removing `InsertChunkRef` breaks the collector test. `internal/app/collector/collector_test.go:126:29: collector.metaDB.InsertChunkRef undefined (type *metadb.MetaDB has no field or method InsertChunkRef)`

We should either add this back in or see if that test can take in `InsertChunkRefAsReady`

**Review by hongalex — CHANGES_REQUESTED** [review]
One test is failing because of the removal of `InsertChunkRef`

File: internal/pkg/metadb/metadb.go (hunk 3 above)
Comment (loranger2k) [reply internal/pkg/metadb/metadb.go:942]: I have modified the implementation so that the call to InsertChunkRef does not modify the status nor the timestamp of the object to be inserted in the function. I also renamed it to its original name.

**Review by hongalex — APPROVED** [review]
